- name: Pause MachineConfigPools
  k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1 
      kind: MachineConfigPool
      metadata:
        name: "{{ item }}"
      spec:
        paused: true
  loop:
    - master
    - worker
