- name: Get existing pull secret
  k8s_info:
    kind: Secret
    name: pull-secret
    namespace: openshift-config
  register: results

- set_fact:
    current_pullsecret: "{{ results.resources[0].data['.dockerconfigjson'] | b64decode }}"

- name: Write current pull secret to file
  copy: 
    content: "{{ current_pullsecret | to_nice_json }}"
    dest: "{{ (backup_dir, 'current_pullsecret.json') | path_join }}"
    backup: true

- set_fact:
    auth_entry: "{{ (new_creds.username + ':' + new_creds.password) | b64encode }}"

- set_fact:
    reg_entry: >-
      {{
        { 
          new_registry:
            {
              'auth': auth_entry
            }
        }
      }}

- set_fact:
    updated_pullsecret: "{{ current_pullsecret | default({}) | combine({'auths':reg_entry},recursive=true) }}"

- name: Write updated pull secret to file
  copy: 
    content: "{{ updated_pullsecret | to_nice_json }}"
    dest: "{{ (backup_dir, 'updated_pullsecret.json') | path_join }}"
    backup: true

- name: Update pull secret on cluster
  k8s:
    definition: 
      apiVersion: v1
      data:
        ".dockerconfigjson": "{{ updated_pullsecret | to_json | b64encode }}"
      kind: Secret
      metadata:
        name: pull-secret
        namespace: openshift-config
    state: present
