- name: "Create working copy of kubeconfig"
  shell: "oc config new-admin-kubeconfig > {{ kc_dir }}/kubeconfig.new"

- name: "Update proper CA bundle"
  shell: "oc config refresh-ca-bundle"
  environment:
    KUBECONFIG: "{{ kc_dir }}/kubeconfig.new"

- name: "Set certificate based user and credentials"
  shell: "oc config set-credentials admin --client-certificate='{{ kc_crt }}' --client-key='{{ kc_key }}' --embed-certs"
  environment:
    KUBECONFIG: "{{ kc_dir }}/kubeconfig.new"
