- name: Validate current kubeconfig works
  kubernetes.core.k8s_info:
    kind: apiserver
    api_version: config.openshift.io/v1
    name: cluster

- name: Prepare storage
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - "{{ cert_dir }}"
    - "{{ kc_dir }}"

- include_tasks: create_certs.yml

- stat:
    path: "{{ kc_dir }}/kubeconfig.new"
  register: kc_new

- include_tasks: create_kc.yml
  when: not kc_new.stat.exists

- include_tasks: create_addtl_cm.yml

- name: Validate new kubeconfig works
  k8s_info:
    api_version: config.openshift.io/v1
    kind: APIServer
    name: cluster
  environment: 
    KUBECONFIG: "{{ kc_dir }}/kubeconfig.new"

- include_tasks: revoke.yml
