- name: Revoke old CA by replacing it with the new one
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "admin-kubeconfig-client-ca"
        namespace: openshift-config
      data:
        ca-bundle.crt: "{{ found_ca_on_api_addtl_cm }}"
  register: revoked

- name: Sleep for a moment to allow system to register change
  ansible.builtin.wait_for:
    timeout: 15
  when: revoked.changed

- name: Check controller operator
  k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterOperator
    name: openshift-controller-manager
  register: co
  until: 
    - co.resources[0].status.conditions | selectattr('type','==','Progressing') | map(attribute='status') | first == 'False'
    - co.resources[0].status.conditions | selectattr('type','==','Degraded') | map(attribute='status') | first == 'False'
    - co.resources[0].status.conditions | selectattr('type','==','Available') | map(attribute='status') | first == 'True'
  retries: 30
  delay: 10
  when: revoked.changed
  environment: 
    KUBECONFIG: "{{ kc_dir }}/kubeconfig.new"

- name: Validate existing kubeconfig now fails
  k8s_info:
    kind: apiServer
  register: get_apiserver
  failed_when: get_apiserver.resources is defined
  environment: 
    KUBECONFIG: "{{ kc_existing_revoke }}"
  
- name: remove the APIserver patch for the additional CA configmap
  kubernetes.core.k8s_json_patch:
    kind: apiserver
    api_version: config.openshift.io/v1
    name: cluster
    patch:
      - op: remove
        path: /spec/clientCA
  when: revoked.changed
  register: removed_addtl_ca
  environment: 
    KUBECONFIG: "{{ kc_dir }}/kubeconfig.new"

- name: Sleep for a moment to allow system to register change
  ansible.builtin.wait_for:
    timeout: 15
  when: removed_addtl_ca.changed

- name: Check controller operator
  k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterOperator
    name: openshift-controller-manager
  register: co
  until: 
    - co.resources[0].status.conditions | selectattr('type','==','Progressing') | map(attribute='status') | first == 'False'
    - co.resources[0].status.conditions | selectattr('type','==','Degraded') | map(attribute='status') | first == 'False'
    - co.resources[0].status.conditions | selectattr('type','==','Available') | map(attribute='status') | first == 'True'
  retries: 30
  delay: 10
  when: removed_addtl_ca.changed
  environment: 
    KUBECONFIG: "{{ kc_dir }}/kubeconfig.new"

- name: remove the additional CA configmap
  k8s:
    kind: ConfigMap
    name: "admin-kubeconfig-client-ca-{{ ca_name }}"
    namespace: openshift-config
    state: absent
  environment: 
    KUBECONFIG: "{{ kc_dir }}/kubeconfig.new"
